version: '3.9'

services:
  nginx:
    depends_on:
      - backend
    build: ./frontend
    container_name: nginx
    volumes:
      - ./frontend/front:/var/www/html
    restart: on-failure
    ports:
      - "81:81"
    networks:
      - frontend

  backend:
    depends_on:
      - db
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/project:/project
    restart: on-failure
    networks:
      - frontend

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: oussama
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - frontend

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - frontend
    # ports:
    #   - "6379:6379" 
networks:
  frontend:
    driver: bridge
volumes:
  postgres_data: